spring:
  datasource:
    url:              jdbc:h2:file:~/alexaOpenHabSkill
    username:         sa
    password:         sa
    driverClassName:  org.h2.Driver
  jpa:
     show-sql: false
     hibernate:
        ddl-auto: update
        
  
server:
  port:         8443
  ssl:
    key-store: ./src/main/resources/ssl/keystore.jks
    key-store-password: password
    

openHab:
  host: localhost
  port: 8080
  
 #test setup for alternate configuration
alexa:
  office:
    switch:
      light: Licht_EG_Buero_Decke
      fishtank: Steckdose_EG_Buero
    rollershutter:
      north: Rollade_EG_Buero_Nord
      east: Rollade_EG_Buero_Ost
    number:
      temperature: Temp_EG_Buero      
    tv:
    dimmer:
    color:
  livingroom:
    switch:
      fishtank: Steckdose_EG_Wohnzimmer_Aquarium_oben
    rollershutter:
      leftdoor: Rollade_EG_Wohnzimmer_SchiebetuerLinks
      rightdoor: Rollade_EG_Wohnzimmer_SchiebetuerRechts
    number:
      temperature: Temp_EG_Wohnzimmer_Sofa
    tv:
      
    dimmer:
      light: Dimmer_EG_Wohnzimmer
    color:
      fireplace: 
    
              