spring:
  datasource:
    url:              jdbc:h2:file:~/alexaOpenHabSkill
    username:         sa
    password:         sa
    driverClassName:  org.h2.Driver
  jpa:
     show-sql: false
     hibernate:
        ddl-auto: update
        
  
server:
  port:         8080
    

              